var cssLayoutString;
var cssLayoutIndex;

var MOBILEWIDTHMAXIMUM = 480;
var TABLETSMALLWIDTHMAXIMUM = 720;
var TABLETLARGEWIDTHMAXIMUM = 1080;

var MAXIMUMPAGEWIDTH = 1440;
var MINIMUMPAGEWIDTH = 320;

